{
 "title": "AFL Fuzzing Metrics",
 "time": { "from": "2026-05-05T05:51:10.128Z", "to": "2026-06-15T02:06:04.033Z" },
 "panels": [
  { "title": "Core Fuzzing Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cumulative Execs/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(fuzzing{type=\"execs_per_sec\", banner=~\"fuzz_parser_afl.*\"})",
     "legendFormat": "parser"
    },
    {
     "expr": "sum(fuzzing{type=\"execs_per_sec\", banner=~\"fuzz_header_afl.*\"})",
     "legendFormat": "header"
    },
    {
     "expr": "sum(fuzzing{type=\"execs_per_sec\", banner=~\"fuzz_server_afl.*\"})",
     "legendFormat": "server"
    }
   ]
  },
  {
   "title": "Total Crashes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(fuzzing{type=\"total_crashes\", banner=~\"fuzz_parser_afl.*\"})",
     "legendFormat": "parser"
    },
    {
     "expr": "sum(fuzzing{type=\"total_crashes\", banner=~\"fuzz_header_afl.*\"})",
     "legendFormat": "header"
    },
    {
     "expr": "sum(fuzzing{type=\"total_crashes\", banner=~\"fuzz_server_afl.*\"})",
     "legendFormat": "server"
    }
   ]
  },
  {
   "title": "Unique Crashes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(fuzzing{type=\"saved_crashes\", banner=~\"fuzz_parser_afl.*\"})",
     "legendFormat": "parser"
    },
    {
     "expr": "sum(fuzzing{type=\"saved_crashes\", banner=~\"fuzz_header_afl.*\", banner!~\".*-(16|23).*\"})",
     "legendFormat": "header"
    },
    {
     "expr": "sum(fuzzing{type=\"saved_crashes\", banner=~\"fuzz_server_afl.*\"})",
     "legendFormat": "server"
    }
   ]
  },
  {
   "title": "Unique Hangs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(fuzzing{type=\"saved_hangs\", banner=~\"fuzz_parser_afl.*\"})",
     "legendFormat": "parser"
    },
    {
     "expr": "sum(fuzzing{type=\"saved_hangs\", banner=~\"fuzz_header_afl.*\"})",
     "legendFormat": "header"
    },
    {
     "expr": "sum(fuzzing{type=\"saved_hangs\", banner=~\"fuzz_server_afl.*\"})",
     "legendFormat": "server"
    }
   ]
  },
  {
   "title": "Cycles Done",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(fuzzing{type=\"cycle_done\", banner=~\"fuzz_parser_afl.*\"})",
     "legendFormat": "parser"
    },
    {
     "expr": "sum(fuzzing{type=\"cycle_done\", banner=~\"fuzz_header_afl.*\"})",
     "legendFormat": "header"
    },
    {
     "expr": "sum(fuzzing{type=\"cycle_done\", banner=~\"fuzz_server_afl.*\"})",
     "legendFormat": "server"
    }
   ]
  },
  {
   "title": "Total Execs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum(fuzzing{type=\"execs_done\", banner=~\"fuzz_parser_afl.*\"})",
     "legendFormat": "parser"
    },
    {
     "expr": "sum(fuzzing{type=\"execs_done\", banner=~\"fuzz_header_afl.*\"})",
     "legendFormat": "header"
    },
    {
     "expr": "sum(fuzzing{type=\"execs_done\", banner=~\"fuzz_server_afl.*\"})",
     "legendFormat": "server"
    }
   ]
  },
  {
   "title": "Cycles Without Finds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "sum(fuzzing{type=\"cycles_wo_finds\", banner=~\"fuzz_parser_afl.*\"})",
     "legendFormat": "parser"
    },
    {
     "expr": "sum(fuzzing{type=\"cycles_wo_finds\", banner=~\"fuzz_header_afl.*\"})",
     "legendFormat": "header"
    },
    {
     "expr": "sum(fuzzing{type=\"cycles_wo_finds\", banner=~\"fuzz_server_afl.*\"})",
     "legendFormat": "server"
    }
   ]
  },
  {
   "title": "Corpus Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max(fuzzing{type=\"corpus_imported\", banner=~\"fuzz_parser_afl.*\"})",
     "legendFormat": "parser"
    },
    {
     "expr": "max(fuzzing{type=\"corpus_imported\", banner=~\"fuzz_header_afl.*\"})",
     "legendFormat": "header"
    },
    {
     "expr": "max(fuzzing{type=\"corpus_imported\", banner=~\"fuzz_server_afl.*\"})",
     "legendFormat": "server"
    }
   ]
  }
 ]
}